################################################################################
#
# Dockerfile for adding opengl into atom (or any debian-based image)
#
################################################################################

ARG BASE_IMAGE=elementaryrobotics/atom
FROM ${BASE_IMAGE} as with-opengl

ARG DEBIAN_FRONTEND=noninteractive

# Potentially install opengl
RUN apt-get update && apt-get install -y \
  --no-install-recommends \
  libglvnd0 \
  libgl1 \
  libglx0 \
  libegl1 \
  libgles2
