FROM redis:alpine

# Install required linux packages
RUN apk add gcc \
            musl-dev \
            g++ \
            make \
            cmake \
            git \

# Install essentials for python
  && apk add python3 \
  && python3 -m ensurepip \
  && pip3 install --upgrade pip setuptools \

# Build and install msgpack
  && pip3 --no-cache-dir install msgpack

ADD ./.gitmodules /atom/.gitmodules

# Install redis-py
ADD ./languages/python/third-party /atom/languages/python/third-party
RUN cd /atom/languages/python/third-party/redis-py && \
    python3 setup.py install

# Build and install arrow
ADD ./third-party/ /atom/third-party/
RUN cd /atom/third-party/ && \
    sh ./install_arrow.sh

ADD . /atom

# Install depedencies for atom-cli
RUN cd /atom/utilities/atom-cli && \
    pip3 install --no-cache-dir -r requirements.txt && \
    cp atom-cli.py /usr/bin/atom-cli && \
    chmod +x /usr/bin/atom-cli

# Build and install python library for atom
RUN cd /atom/languages/python && \
    pip3 install --no-cache-dir -r requirements.txt && \
    python3 setup.py install

# Change directory to nucleus and chown the launch script
ADD ./launch_nucleus.sh /nucleus/launch.sh
ADD ./redis.conf /nucleus/redis.conf
RUN cd /nucleus && \
    chmod +x launch.sh
CMD ["./launch.sh"]
