ARG BASE_IMAGE_TAG=2412f998eb0164403bef162a586bb0fe303441b1
ARG BASE_IMAGE=atom-base
FROM elementaryrobotics/$BASE_IMAGE:$BASE_IMAGE_TAG

# Want to copy over the contents of this repo to the code
#	section so that we have the source
ADD . /atom

#
# Build and install the python library
#
WORKDIR /atom/languages/python
RUN pip3 install -r requirements.txt
RUN python3 setup.py install

#
# Build and install the c library
#

# Need to first build hiredis
WORKDIR /atom/languages/c/third-party/hiredis
RUN make clean && make && make install LIBRARY_PATH=lib

# And build the C library
WORKDIR /atom/languages/c
RUN make clean && make && make install

#
# Build and install the c++ library
#

WORKDIR /atom/languages/cpp
RUN make clean && make && make install

#
# Install dependencies for atom-cli
#
WORKDIR /atom/utilities/atom-cli
RUN pip3 install -r requirements.txt
RUN cp atom-cli.py /usr/bin/atom-cli
RUN chmod +x /usr/bin/atom-cli
