################################################################################
#
# Dockerfile for adding VNC into atom (or any debian-based image)
#
################################################################################

ARG BASE_IMAGE=elementaryrobotics/atom
FROM ${BASE_IMAGE} as with-vnc

ARG DEBIAN_FRONTEND=noninteractive

# Add in noVNC to /opt/noVNC
ADD third-party/noVNC /opt/noVNC

# Install graphics
# Note: supervisor-stdout must be installed with pip2 and not pip3
RUN apt-get install -y --no-install-recommends \
      libgl1-mesa-dri \
      menu \
      net-tools \
      openbox \
      supervisor \
      tint2 \
      x11-xserver-utils \
      x11vnc \
      xinit \
      xserver-xorg-video-dummy \
      xserver-xorg-input-void \
      websockify \
      python-pip \
 && rm -f /usr/share/applications/x11vnc.desktop \
# VNC
 && cd /opt/noVNC \
 && ln -s vnc_auto.html index.html \
 && pip2 install --no-cache-dir setuptools \
 && pip2 install --no-cache-dir supervisor-stdout \
 && apt-get -y remove python-pip \
 && apt-get -y autoremove \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

# noVNC (http server) is on 6080, and the VNC server is on 5900
EXPOSE 6080 5900
COPY third-party/docker-opengl/etc/skel/.xinitrc /etc/skel/.xinitrc

RUN useradd -m -s /bin/bash user
USER user
RUN cp /etc/skel/.xinitrc /home/user/
USER root
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user

COPY third-party/docker-opengl/etc /etc
COPY third-party/docker-opengl/usr /usr

# Need to run app with python2 instead of python3
RUN var='#!/usr/bin/env python2' \
 && sed -i "1s@.*@${var}@" /usr/bin/graphical-app-launcher.py

ENV DISPLAY :0
