ARG BASE_IMAGE=debian:buster-slim
FROM $BASE_IMAGE as base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends apt-utils \
                                               git autoconf \
                                               libtool \
                                               cmake \
                                               build-essential \
                                               python3-minimal \
                                               python3-pip \
                                               python3-venv \
 && pip3 install --no-cache-dir --upgrade pip setuptools

# Create and activate python virtualenv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install msgpack
RUN pip3 install --no-cache-dir msgpack \
 && cd /usr/src && git clone https://github.com/msgpack/msgpack-c.git \
 && cd /usr/src/msgpack-c && cmake -DMSGPACK_CXX11=ON . && make install

# Install redis-py
ADD ./languages/python/third-party/redis-py /atom/languages/python/third-party/redis-py
RUN cd /atom/languages/python/third-party/redis-py \
 && python3 setup.py install

# Build hiredis for C library
ADD ./languages/c/third-party/hiredis /atom/languages/c/third-party/hiredis
RUN cd /atom/languages/c/third-party/hiredis \
 && make && make install LIBRARY_PATH=lib

# Build the C library
ADD ./languages/c /atom/languages/c
RUN cd /atom/languages/c \
 && make clean && make && make install

# Build and install the c++ library
ADD ./languages/cpp /atom/languages/cpp
RUN cd /atom/languages/cpp \
 && make clean && make && make install

# Build and install the python library
# Add and install requirements first to use DLC
ADD ./languages/python/requirements.txt /atom/languages/python/requirements.txt
RUN pip3 install --no-cache-dir -r /atom/languages/python/requirements.txt
ADD ./utilities/atom-cli/requirements.txt /atom/utilities/atom-cli/requirements.txt
RUN pip3 install --no-cache-dir -r /atom/utilities/atom-cli/requirements.txt

# Install atom-cli
ADD ./utilities/atom-cli /atom/utilities/atom-cli
RUN cp /atom/utilities/atom-cli/atom-cli.py /usr/local/bin/atom-cli \
 && chmod +x /usr/local/bin/atom-cli

ADD ./languages/python /atom/languages/python
ADD ./lua-scripts /atom/lua-scripts
RUN cd /atom/languages/python \
 && python3 setup.py install

# Change working directory back to atom location
WORKDIR /atom




FROM $BASE_IMAGE as prod

# Cache buster env var - change date to invalidate subsequent caching
# See the atom README "Atom Dockerfile" section for more information
ENV LAST_UPDATED 2019-03-06

# Install python
RUN apt-get update -y \
 && apt-get install -y --no-install-recommends apt-utils \
                                               python3-minimal \
                                               python3-pip

# Copy contents of python virtualenv and activate
COPY --from=base /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Set up LD_LIBRARY_PATH s.t. the C/C++ binaries can be found
ENV LD_LIBRARY_PATH /lib:/usr/local/lib

# Copy C builds
COPY --from=base /usr/local/lib /usr/local/lib
COPY --from=base /usr/local/include /usr/local/include

# Copy atom-cli
COPY --from=base /usr/local/bin/atom-cli /usr/local/bin/atom-cli

# Add .circleci for docs build
ADD ./.circleci /atom/.circleci

# Change working directory back to atom location
WORKDIR /atom




FROM prod as test

ARG DEBIAN_FRONTEND=noninteractive

#
# Install test dependencies
#

# Cache buster env var - change date to invalidate subsequent caching
# See the atom README "Atom Dockerfile" section for more information
ENV LAST_UPDATED 2019-03-12

# Install googletest
RUN apt-get update \
 && apt-get install -y --no-install-recommends libgtest-dev cmake build-essential \
 && cd /usr/src/gtest \
 && cmake CMakeLists.txt && make -j16 && cp *.a /usr/lib

# Install valgrind
RUN apt-get install -y --no-install-recommends valgrind

# Install pytest
RUN pip3 install --no-cache-dir pytest

# Copy source code
COPY ./languages/c/ /atom/languages/c
COPY ./languages/cpp/ /atom/languages/cpp
COPY ./languages/python/tests /atom/languages/python/tests




FROM prod as graphics

ARG DEBIAN_FRONTEND=noninteractive

# Install graphics
# Note: supervisor-stdout must be installed with pip2 and not pip3
RUN apt-get install -y --no-install-recommends \
      libgl1-mesa-dri \
      menu \
      net-tools \
      openbox \
      supervisor \
      tint2 \
      x11-xserver-utils \
      x11vnc \
      xinit \
      xserver-xorg-video-dummy \
      xserver-xorg-input-void \
      websockify \
      git \
      sudo \
      python-pip \
 && rm -f /usr/share/applications/x11vnc.desktop \
# VNC
 && git clone https://github.com/kanaka/noVNC.git /opt/noVNC \
 && cd /opt/noVNC \
 && git checkout 6a90803feb124791960e3962e328aa3cfb729aeb \
 && ln -s vnc_auto.html index.html \
 && pip2 install --no-cache-dir setuptools \
 && pip2 install --no-cache-dir supervisor-stdout \
 && apt-get -y remove python-pip git \
 && apt-get -y autoremove \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*

# noVNC (http server) is on 6080, and the VNC server is on 5900
EXPOSE 6080 5900
COPY third-party/docker-opengl/etc/skel/.xinitrc /etc/skel/.xinitrc

RUN useradd -m -s /bin/bash user
USER user
RUN cp /etc/skel/.xinitrc /home/user/
USER root
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user

COPY third-party/docker-opengl/etc /etc
COPY third-party/docker-opengl/usr /usr

# Need to run app with python2 instead of python3
RUN var='#!/usr/bin/env python2' \
 && sed -i "1s@.*@${var}@" /usr/bin/graphical-app-launcher.py

ENV DISPLAY :0
