#installs cudnn into a base image
#Set the base image below.
#Then typical usage is:
#docker build -f Dockerfile-install-cudnn -t atom-xxxxxx-base .
#(where xxxxxx is up to the user, typically it matches
#an image on dockerhub that the user wants to update)
#Assumes that the user has downloaded the cudnn .deb installer
#to the current folder and the name matches the second ARG statement below

ARG BASE_IMAGE=nvidia/cudagl:10.1-runtime-ubuntu18.04
FROM $BASE_IMAGE

ARG CUDNN_FILE=libcudnn7_7.6.5.32-1+cuda10.1_amd64.deb

ADD $CUDNN_FILE /$CUDNN_FILE

WORKDIR /

#install cudnn
RUN dpkg -i $CUDNN_FILE
RUN rm $CUDNN_FILE
