ARG BASE_IMAGE_TAG=33e20b3be1d5fa6e7825a8438db4c53c2e15ab65
ARG BASE_IMAGE=atom-base
FROM elementaryrobotics/$BASE_IMAGE:$BASE_IMAGE_TAG AS builder

#
# Install redis-py
#
ADD ./languages/python/third-party/redis-py /atom/languages/python/third-party/redis-py
RUN cd /atom/languages/python/third-party/redis-py \
 && python3 setup.py install --user

#
# Build and install the c library
#

# Need to first build hiredis
ADD ./languages/c/third-party/hiredis /atom/languages/c/third-party/hiredis
RUN cd /atom/languages/c/third-party/hiredis \
 && make && make install LIBRARY_PATH=lib

# And build the C library
ADD ./languages/c /atom/languages/c
RUN cd /atom/languages/c \
 && make clean && make && make install

#
# Build and install the c++ library
#
ADD ./languages/cpp /atom/languages/cpp
RUN cd /atom/languages/cpp \
 && make clean && make && make install

#
# Build and install the python library
#
ADD ./languages/python /atom/languages/python
ADD ./lua-scripts /atom/lua-scripts
RUN cd /atom/languages/python \
 && pip3 install --user --no-cache-dir -r requirements.txt \
 && python3 setup.py install --user

#
# Install dependencies for atom-cli
#
ADD ./utilities/atom-cli /atom/utilities/atom-cli
RUN cd /atom/utilities/atom-cli \
 && pip3 install --user --no-cache-dir -r requirements.txt


FROM elementaryrobotics/$BASE_IMAGE:$BASE_IMAGE_TAG

COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
# Need to copy over C builds here

ADD ./utilities/atom-cli /atom/utilities/atom-cli
RUN cd /atom/utilities/atom-cli \
 && cp atom-cli.py /usr/bin/atom-cli \
 && chmod +x /usr/bin/atom-cli

# Change working directory back to atom location
WORKDIR /atom
