################################################################################
#
# Dockerfile for minimizing a build and only copying over
#   libraries and the python virtual environment
#
################################################################################

# Previous base we're going to build atop
ARG BASE_IMAGE
# Image this version of atom will ship with. Needed to determine which
#   libraries we need to package up
ARG PRODUCTION_IMAGE

#
# Determine libraries that are already in production
#
FROM ${PRODUCTION_IMAGE} as no-deps
# Auto-set by Docker based on the --platform flag
ARG TARGETPLATFORM

RUN ls /lib/$( echo ${TARGETPLATFORM} | sed s/amd64/x86_64/g )-linux-gnu/*.so* > /tmp/existing_libs.txt && \
    ls /usr/lib/$( echo ${TARGETPLATFORM} | sed s/amd64/x86_64/g )-linux-gnu/*.so* >> /tmp/existing_libs.txt

#
# Copy missing libraries into /usr/local/lib
#
FROM ${BASE_IMAGE} as with-deps
ARG REQUIRED_LIBS

# Figure out which libraries we need
ldd ${REQUIRED_LIBS} | grep "=> /" | awk '{print $3}' | sort -u > /tmp/required_libs.txt

# Copy over the file that lets us know what's already in the final
#   image we're being built atop
COPY --from=no-deps /tmp/existing_libs.txt /tmp/existing_libs.txt

# Figure out what we need to copy into /usr/local/lib.
RUN diff --new-line-format="" --unchanged-line-format=""  /tmp/required_libs.txt /tmp/existing_libs.txt | grep -v /usr/local/lib > /tmp/libs_to_copy.txt

# Copy things into /usr/local/lib
RUN xargs -a /tmp/libs_to_copy.txt cp -L -t /usr/local/lib

#
# Clean up and only ship the following folders:
#   1. /usr/local/lib
#   2. /usr/local/include
#   3. /opt/venv
#
FROM ${PRODUCTION_IMAGE} as minimized

COPY --from=with-deps /usr/local/lib /usr/local/lib
COPY --from=with-deps /usr/local/include /usr/local/include
COPY --from=with-deps /opt/venv /opt/venv
